#spring.application.name=springsecuritystarter
logging:
  level:
    org.springframework.security: trace
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss}) | %highlight(%p)  | %yellow(%m) | %cyan(%c{1.}) %n"
server:
  port: 8081
#
#oauth2:
#  client:
#    client-id: ${GITHUB_CLIENT_ID}
#    client-secret: ${GITHUB_CLIENT_SECRET}
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_URI}
